version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: andrey223/food_backend
    env_file: .env
    volumes:
      - static:/backend_static
    ports:
      - 8000:8000
    depends_on:
      - db
  gateway:
    image: andrey223/food_gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8080:80