version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./gateway.conf:/etc/gateway/conf.d/default.conf
      - ../frontend/build:/usr/share/gateway/html/
      - ../docs/:/usr/share/gateway/html/api/docs/
