# Generated by Django 3.2.25 on 2024-07-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resept', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(max_length=255, related_name='recipes', to='resept.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
